services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:cached       # mount code for live reload
      - /usr/src/app/node_modules   # keep container's node_modules intact
  mongo:
    image: mongo